spring:
  application:
    name: protomeme
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chat}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

minio:
  url: ${MINIO_URL:http://localhost:9000/}
  username: ${MINIO_USERNAME:minioadmin}
  password: ${MINIO_PASSWORD:minioadmin}
  bucket: ${MINIO_BUCKET:files}